{% set name = "pex" %}
{% set version = "2.28.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pex-{{ version }}.tar.gz
  sha256: 497411a299ef42c60a3ba26b3daaf28787a828ca0d7d3e46cb5b610aef40f54c

build:
  entry_points:
    - pex = pex.bin.pex:main
    - pex3 = pex.cli.pex:main
    - pex-tools = pex.tools.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - pygithub
    - toml
    - ansicolors
    - coloredlogs
    - cryptography
    - genshi
    - hatchling
    - httpx
    - lxml
    - pyopenssl
    - pyyaml
    - redbaron
    - python >=3.8
    - __unix  # [unix]
    - __win   # [win]

test:
  imports:
    - pex
  commands:
    - pip check
    - pex --help
    - pex3 --help
    - pex-tools --help
  requires:
    - pip

about:
  home: https://github.com/pex-tool/pex
  summary: The PEX packaging toolchain.
  dev_url: https://github.com/pex-tool/pex/tree/v2.4.0
  license: Unlicense AND BSD-2-Clause AND MIT AND Apache-2.0
  license_file:
    - LICENSE
    - pex/vendor/_vendored/toml/toml-0.10.2.dist-info/LICENSE
    - pex/vendor/_vendored/attrs/attrs-21.5.0.dev0.dist-info/LICENSE
    - pex/vendor/_vendored/pip/pip-20.3.4.dist-info/LICENSE.txt
    - pex/vendor/_vendored/packaging_20_9/packaging-20.9.dist-info/LICENSE
    - pex/vendor/_vendored/packaging_20_9/packaging-20.9.dist-info/LICENSE.APACHE
    - pex/vendor/_vendored/packaging_20_9/packaging-20.9.dist-info/LICENSE.BSD
    - pex/vendor/_vendored/packaging_20_9/pyparsing-2.4.7.dist-info/LICENSE
    - pex/vendor/_vendored/packaging_23_1/packaging-23.1.dist-info/LICENSE
    - pex/vendor/_vendored/packaging_23_1/packaging-23.1.dist-info/LICENSE.APACHE
    - pex/vendor/_vendored/packaging_23_1/packaging-23.1.dist-info/LICENSE.BSD
    - pex/vendor/_vendored/setuptools/setuptools-44.0.0+3acb925dd708430aeaf197ea53ac8a752f7c1863.dist-info/LICENSE
    - pex/vendor/_vendored/packaging_21_3/pyparsing-2.4.7.dist-info/LICENSE
    - pex/vendor/_vendored/packaging_21_3/packaging-21.3.dist-info/LICENSE
    - pex/vendor/_vendored/packaging_21_3/packaging-21.3.dist-info/LICENSE.APACHE
    - pex/vendor/_vendored/packaging_21_3/packaging-21.3.dist-info/LICENSE.BSD

extra:
  recipe-maintainers:
    - geoHeil
    - tmirko
    - milicevica23
